version: '3.3'

services:
  web:

    container_name: storm-score-new
    image: wammelier4417/storm-score-new:1.0
    ports:
      - "8443:8443"
    restart: always
    volumes:
      - /home/ec2-user/storm_score/logs:/logs
    environment:
      - TZ=Asia/Seoul