name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main" ]  # main으로 PR시 Actions 작동
  push:
    branches: [ "ojy" ]  # main으로 push시 Actions 작동

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Checkout private repository
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/StormManager/storm_score_sub.git
          cd storm_score_sub/src
          
          cp * ../../src/main/resources/
          
          ls

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      # https://github.com/docker/build-push-action
      # docker 시작
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_ID}}
          password: ${{secrets.DOCKER_PWD}}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .  # base folder
          file: ./Dockerfile # Dockerfile path
          platforms: linux/amd64 # m1에서는 - linux/arm64/v8
          push: true                                       # github 저장소 명으로 도커 imagename 설정 
          tags: wammelier4417/${{ github.event.repository.name }}:1.0
